### PR TITLE
[nfc] Reorganize and Rename Appendices

### PR DESCRIPTION
**Pull request by mmaloney-sf**
- Move "Primitive Operations" section closer to the bottom.
- Rename a "FIRRTL Language Definition" to "Grammar".
- Rename "Details about Syntax" to "Notes on Syntax".

### CODE REVIEW

**Review by seldridge — APPROVED** [review]

**Comment by seldridge** [comment]
Only thing that would be good for this type of thing is to add entries to the `revision-history.yaml` and to use commit/PR tags. E.g., `[nfc]`.

**Comment by mmaloney-sf** [comment]
@seldridge Done.

I'm a little worried about spamming the revision section with all the changes I want to make during this reorganization effort. Any thoughts on how to mitigate that?

**Comment by seldridge** [comment]
It's fine if there wind up being a lot of entries. Alternatively, the revision-history can just be amended. Obviously, don't edit anything in `oldVersions`. However, `thisVersion` can be updated as opposed to always adding new items.

**Comment by mmaloney-sf** [comment]
I'm also moving the "Literals" section. It feels like it got separated from the herd. It's not important enough for its own top-level section, and I'm sticking it under the "Notes on Syntax" section. 

I'm also removing the heading on radix-specified integer literals. (The content is still there).

**Pull request merged**
