### PR TITLE
[major] No abstract reset on extmodule.

### PR DESCRIPTION
**Pull request by dtzSiFive**
Align extmodule port requirements re:abstract reset to match those on "public".

### CODE REVIEW

**Review by seldridge — APPROVED** [review]
LGTM

Please add tests/issues to Chisel or x-fail tests to CIRCT as I don't think this is currently rejected.

Chisel doesn't currently enforce and CIRCT doesn't check it.

CC: @jackkoenig

**Comment by seldridge** [comment]
This one has users and, after talking with @dtzSiFive, it would be better to hold off on this for 4.0.0 so we can figure out how to get Chisel to stop emitting this.

**Comment by darthscsi** [comment]
> so we can figure out how to get Chisel to stop emitting this.

Is it Chisel or code bases using it which do this?  If it's just code-bases and there is nothing in Chisel forcing this, then that's an easier transition.

**Comment by jackkoenig** [comment]
> Is it Chisel or code bases using it which do this? If it's just code-bases and there is nothing in Chisel forcing this, then that's an easier transition.

Chisel does **not** do this, the only things that get abstract reset automatically in Chisel are normal Modules (i.e. not extmodules) that are not the top module.

**Review by mmaloney-sf — APPROVED** [review]

**Pull request merged**
